# Entity: Configuration
# Configuration management and environment setup
name: configuration
display_name: "Configuration"
description: "Configuration management and environment setup entity"
provider: "openai"
model: "gpt-4"
capabilities:
  allowed_paths: []
  allowed_actions: []
  branch_prefix: "ops/configuration"
permissions:
  read: false
  write: false
  create_pr: false
