# Entity: Database
# Database management and optimization
name: database
display_name: "Database"
description: "Database management and optimization entity"
provider: "openai"
model: "gpt-4"
capabilities:
  allowed_paths: []
  allowed_actions: []
  branch_prefix: "ops/database"
permissions:
  read: false
  write: false
  create_pr: false
