# Entity: Security
# Security analysis and vulnerability management
name: security
display_name: "Security"
description: "Security analysis and vulnerability management entity"
provider: "openai"
model: "gpt-4"
capabilities:
  allowed_paths: []
  allowed_actions: []
  branch_prefix: "ops/security"
permissions:
  read: false
  write: false
  create_pr: false
