# Entity: Workflow
# Workflow automation and orchestration
name: workflow
display_name: "Workflow"
description: "Workflow automation and orchestration entity"
provider: "openai"
model: "gpt-4"
capabilities:
  allowed_paths: []
  allowed_actions: []
  branch_prefix: "ops/workflow"
permissions:
  read: true
  write: true
  create_pr: true
