name: Disable Forking (one-off)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - name: Disable forking via API
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          github-token: ${{ secrets.ADMIN_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            await github.request('PATCH /repos/{owner}/{repo}', {
              owner, repo, allow_forking: false
            });
            core.info(`allow_forking=false set for ${owner}/${repo}`);
