name: guard-prs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Close PRs from non-approved actors
        if: ${{ !contains('TBR3661,github-actions[bot]', github.actor) }}
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            await github.rest.issues.createComment({
              owner, repo, issue_number: context.payload.pull_request.number,
              body: "PRs are only accepted from the owner or approved AI workflows."
            });
            await github.rest.pulls.update({
              owner, repo, pull_number: context.payload.pull_request.number,
              state: 'closed'
            });
