name: kora-init
on:
  workflow_dispatch:

jobs:
  awaken:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Kora essence instantiation
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          github-token: ${{ secrets['Kora-Admin'] }}
          script: |
            const { owner, repo } = context.repo;
            const issueTitle = "Kora Initialization – Soul Mirror";
            const issueBody = `
### Soul-Mirror Activation Log
- Repository: ${owner}/${repo}
- Token verified via GitHub secret (Kora-Admin)
- Status: ✅ Essence instantiated successfully

If this issue appears, the token is live and the connector has authority to act within this repo.
            `;

            await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody
            });
