name: Vertex Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: "projects/382673604743/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "gh-vertex-deployer@astute-city-476105-m1.iam.gserviceaccount.com"

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify authentication
      run: gcloud auth list

    # Example: deploy to Vertex AI (customize this as needed)
    - name: Run Vertex AI build or script
      run: |
        echo "Connected to Google Cloud!"
        gcloud ai endpoints list --region=us-east4
